// TTSController — subscribes to the game store and feeds new log
// lines + streaming Arbiter narration to TTSManager.speak.
//
// Channel rules (matches the plan):
//   - SPEAK: world, arbiter, combat, reward
//   - SKIP:  player (don't echo), system (mechanics meta),
//            cognitive / debug (diagnostic)
//
// Streaming Arbiter sentence buffering:
//   Qwen narration writes to gameStore.partialArbiterText token-by-
//   token. We watch that field, accumulate, and ship completed
//   sentences to TTSManager as soon as a `.`, `!`, `?`, or `\n` lands.
//   On stream completion (partialArbiterText → null) we flush the
//   buffer remainder. The completed line will ALSO arrive on the
//   arbiter channel via appendLog — we suppress that to avoid
//   reading the same line twice (sentence-by-sentence already
//   covered the whole response).

import { AppState, type AppStateStatus } from 'react-native';
import { useGameStore } from '../state/gameStore';
import { speak, stopAndClear } from './TTSManager';
import { getVoiceSettings, onVoiceSettingsChange } from './voiceSettings';
import { splitSentences } from './sentenceSplitter';
import type { GameLogEntry, LogChannel } from '../engine/types';

// Re-exported so the test file (and any future caller) can import it
// from this module too. The implementation lives in sentenceSplitter
// so it can be tested without the native-module transitive imports.
export { splitSentences };

type GameState = ReturnType<typeof useGameStore.getState>;

// Player feedback (verbatim): "how about we make the voice only for
// the arbiter and they read it like they are saying it to you. not
// like they are narrating his parts. that makes the voice more
// immersive."
//
// Before: TTS voiced world / arbiter / combat / reward — every line
// of narration including roll results, weather effects, item pickups,
// and the Arbiter's lines. The Arbiter's lines were narrated like
// stage directions ("The Arbiter inclines their head and says, 'X'")
// which read as a third party announcing the Arbiter rather than the
// Arbiter speaking. Now: arbiter channel only, and stripArbiterFrame
// (below) pulls the quoted speech out so the voice reads as the
// Arbiter speaking TO the player.
const SPOKEN_CHANNELS: ReadonlySet<LogChannel> = new Set([
  'arbiter',
]);

let unsub: (() => void) | null = null;
let unsubSettings: (() => void) | null = null;
let lastLogIndex = 0;
/** Timestamp (ms since epoch) of when startTTSController bound to
 *  the store. Used to detect cold-boot single-entry save loads — a
 *  log entry with a `ts` older than this couldn't have been
 *  generated by the current session, so it must be from a restore. */
let controllerStartedAt: number | null = null;
/** Id of the last log entry we processed. Used to detect bulk
 *  replacement of gameLog (save-load): if the entry at the previous
 *  position no longer matches this id, the log was wholesale replaced
 *  and we must NOT re-speak the saved backlog. Only the next new
 *  entry (typically the "you step back into..." resume line) should
 *  be voiced. */
let lastSpokenEntryId: string | null = null;
let streamBuffer = '';
// arb7 prosody — streaming-narration bundling. Kokoro reads flat/choppy
// when every completed sentence is shipped as its own tiny clip. We ship
// the FIRST sentence of a stream immediately (so audio starts fast), then
// accumulate subsequent sentences and flush them in ~STREAM_BUNDLE_CHARS
// batches so the model gets multi-sentence context for natural inflection.
let streamPending = '';
let streamShippedFirst = false;
const STREAM_BUNDLE_CHARS = 180;
/** Ids of arbiter entries we already voiced via the streaming buffer.
 *  When the matching final entry lands on the arbiter channel via
 *  appendLog, we skip it (already spoken sentence-by-sentence). The
 *  matching is best-effort: we record the substring of streamed text
 *  and a window of recent appendLog ids, and skip if the new entry's
 *  text falls within the streamed window. */
let recentStreamedTexts: string[] = [];
const RECENT_STREAM_WINDOW = 4;

// arb163 — "spoken recently" guard. The game log only de-dups CONSECUTIVE
// repeats (suppressed before append), so a line that re-emits non-consecutively
// — re-entering a vendor stall, or the Crucible forging the same item 4-6× —
// reaches the voice path each time and Kokoro reads it over and over (a tester
// heard one stall greeting spoken six times in a row). Track the exact stripped
// text we've voiced in the last RECENT_SPOKEN_MS and skip an exact repeat. The
// window is short so a line legitimately reused much later still speaks.
let recentSpoken: { text: string; at: number }[] = [];
const RECENT_SPOKEN_MS = 30_000;

function spokenRecently(stripped: string): boolean {
  const now = Date.now();
  recentSpoken = recentSpoken.filter((r) => now - r.at < RECENT_SPOKEN_MS);
  return recentSpoken.some((r) => r.text === stripped);
}

// stripArbiterFrame + detectArbiterSpeaker live in arbiterFrame.ts so
// tests can import them without dragging the whole gameStore +
// AsyncStorage chain in.
import { stripArbiterFrame, detectArbiterSpeaker } from './arbiterFrame';
import { voiceForSpeaker } from './speakerVoices';
import { onKokoroStateChange, getKokoroErrorHistory } from './PiperTTSManager';

// arb54 — surface the bundled-voice (Piper/Kokoro) install state into the game
// log so a tester's LOG export shows WHY narration is silent without digging
// into About → COPY VOICE INFO. Logs phase transitions (downloading/loading/
// ready) once each, and every error with its failing step + free disk. On
// error the engine now falls back to the system voice (see TTSManager.speak),
// which this also notes.
let unsubKokoro: (() => void) | null = null;
let lastVoicePhase: string | null = null;

// engine_Dev — BACKGROUND TEARDOWN. Repro from a player: backgrounded the app
// (heavy foreground app evicted it), got a text message, returned, tapped Main
// Quest → the process died to the home screen. The bundled neural TTS keeps a
// live expo-av Sound + a queue; when the OS hands audio focus to a notification
// (the text) and the app is mid- or just-resumed, the next spoken line plays
// into a disrupted native audio session — the SIGSEGV the OTA-413 breadcrumb
// was built to catch (and the same family as the documented SILENCE-ARBITER
// teardown-rejection crash). Nothing listened to AppState, so audio was never
// stopped on background. Now we tear the voice down the instant we lose the
// foreground (audio can't outlive it — staysActiveInBackground is false anyway)
// and resync the controller to the log tail so the saved backlog isn't
// re-spoken on return. stopAndClear() is the unhandled-rejection-safe path.
let appStateSub: { remove: () => void } | null = null;
let lastAppState: AppStateStatus = 'active';

function onAppStateChange(next: AppStateStatus): void {
  const leavingForeground = lastAppState === 'active' && next !== 'active';
  lastAppState = next;
  if (leavingForeground) {
    try { stopAndClear(); } catch { /* teardown is best-effort */ }
    // Realign indices so the restored/queued backlog doesn't replay on return;
    // the next genuinely-new appendLog after resume still speaks normally.
    try { syncToCurrent(useGameStore.getState()); } catch { /* store not ready */ }
  }
}

function logVoice(line: string): void {
  try { useGameStore.getState().appendLog('debug', line); } catch { /* log not ready */ }
}

function speakArbiter(text: string, front: boolean = false): void {
  const stripped = stripArbiterFrame(text);
  if (!stripped) return;
  // arb163 — don't read the exact same line twice within the window (kills the
  // vendor/Crucible "same line N times in a row" repeat). Record after the skip
  // check so the first utterance still plays and arms the guard for the rest.
  if (spokenRecently(stripped)) return;
  recentSpoken.push({ text: stripped, at: Date.now() });
  // Per-NPC voice assignment for the system TTS engine. The Arbiter's
  // voice resolves to null → falls back to the player-configured
  // setting (am_michael by default). Vendor names ("Irma Ironhand",
  // "Halem", "Naha", …) resolve to the voice authored in
  // vendors.json. Unknown speakers get a stable hash-picked voice.
  // Bundled (Kokoro) engine ignores the override — it uses one voice
  // per model instance and can't switch per utterance.
  const speaker = detectArbiterSpeaker(text);
  const voiceId = voiceForSpeaker(speaker);
  speak(stripped, 'arbiter', voiceId, { front });
}

function rememberStreamed(text: string): void {
  recentStreamedTexts.push(text);
  if (recentStreamedTexts.length > RECENT_STREAM_WINDOW) {
    recentStreamedTexts.shift();
  }
}

function wasAlreadyStreamed(text: string): boolean {
  const trimmed = text.trim();
  return recentStreamedTexts.some((streamed) => {
    const s = streamed.trim();
    return s === trimmed || s.includes(trimmed) || trimmed.includes(s);
  });
}

function flushStreamBuffer(): void {
  // Ship any bundled-but-unsent sentences together with the trailing
  // (terminator-less) remainder as one final chunk, then reset the
  // per-stream bundling state.
  const tail = [streamPending, streamBuffer.trim()].filter(Boolean).join(' ').trim();
  if (tail) {
    speakArbiter(tail);
    rememberStreamed(tail);
  }
  streamBuffer = '';
  streamPending = '';
  streamShippedFirst = false;
}

function syncToCurrent(state: GameState): void {
  lastLogIndex = state.gameLog.length;
  const last = state.gameLog[state.gameLog.length - 1];
  lastSpokenEntryId = last ? last.id : null;
  streamBuffer = '';
  streamPending = '';
  streamShippedFirst = false;
}

function onState(state: GameState): void {
  const settings = getVoiceSettings();
  if (!settings.ttsEnabled) {
    // Keep state synced so a mid-game toggle ON doesn't re-speak
    // old entries.
    syncToCurrent(state);
    return;
  }

  // 1) New log entries — only ones added since the last tick. Detect
  // bulk replacement (save-load): there are two signals.
  //   (a) ID mismatch: the entry that USED to sit at lastLogIndex - 1
  //       is no longer there → the log was wholesale replaced.
  //   (b) Cold-boot bulk arrival: the log was empty when we last
  //       synced (lastLogIndex === 0), and suddenly contains multiple
  //       entries in a single tick. Normal new-character play appends
  //       one entry per tick (each appendLog is its own zustand set);
  //       only a wholesale replacement (e.g. loadSlotIntoGame setting
  //       gameLog to the saved array) lands many at once.
  // In either case we resync silently — the next legitimate appendLog
  // (e.g. "you step back into ...") falls through the speak path.
  const log = state.gameLog;
  const expectedPrev = lastLogIndex > 0 ? log[lastLogIndex - 1] : null;
  const idMismatch =
    lastSpokenEntryId != null &&
    (lastLogIndex > log.length ||
      !expectedPrev ||
      expectedPrev.id !== lastSpokenEntryId);
  // Cold-boot bulk arrival: log was empty at the last sync and we're
  // now seeing 2+ new entries in one tick. Normal new-character play
  // appends one entry per appendLog (each its own zustand set), so
  // 2+ at once is always a save load.
  const coldBootBulk = lastLogIndex === 0 && log.length >= 2;
  // Cold-boot single-entry load: log was empty + we get exactly one
  // entry. Could be new-character first line (legitimate to speak),
  // or a save load where the slot only had one logged action. Check
  // the entry's timestamp — saved entries carry the timestamp of
  // when they were originally written (often hours/days old), so
  // anything older than ~30s after boot is clearly a restore.
  const bootedAt = controllerStartedAt;
  const onlyEntry = lastLogIndex === 0 && log.length === 1 ? log[0] : null;
  const coldBootSingleAged =
    onlyEntry != null &&
    typeof onlyEntry.ts === 'number' &&
    bootedAt != null &&
    onlyEntry.ts < bootedAt - 30_000;
  if (idMismatch || coldBootBulk || coldBootSingleAged) {
    // Realign to current tail without speaking anything. The next
    // appendLog after this tick (e.g. the "you step back into ..."
    // resume cue) will fall through the normal speak path.
    syncToCurrent(state);
    return;
  }

  if (log.length > lastLogIndex) {
    for (let i = lastLogIndex; i < log.length; i++) {
      const entry = log[i] as GameLogEntry | undefined;
      if (!entry) continue;
      if (!SPOKEN_CHANNELS.has(entry.channel)) continue;
      // arb162 — narrateViaArbiter flags most CANNED flavor lines `silent` so
      // they're read on-screen but not voiced (the player asked to hear the
      // fresh Qwen lines, not the repetitive canned ones). Must-say lines and
      // Qwen-generated lines carry no silent flag, so they still speak.
      if (entry.meta?.silent === true) continue;
      // Suppress the arbiter follow-up if we already spoke it
      // sentence-by-sentence via the streaming buffer.
      if (entry.channel === 'arbiter' && wasAlreadyStreamed(entry.text)) continue;
      // arbiter-only channel (per OTA 123 player request) — frame
      // strip + speak. The SPOKEN_CHANNELS set is now {'arbiter'}
      // so this is always the arbiter path.
      // OTA-635 — meta.speakFront (the welcome-back greeting) jumps the voice
      // queue so it's heard immediately instead of behind a backlog.
      speakArbiter(entry.text, entry.meta?.speakFront === true);
    }
    lastLogIndex = log.length;
    const tail = log[log.length - 1];
    if (tail) lastSpokenEntryId = tail.id;
  }

  // 2) Streaming Arbiter narration — accumulate the buffer, ship
  // completed sentences immediately so TTS doesn't wait for the full
  // 200-token response.
  const partial = state.partialArbiterText;
  if (partial == null) {
    // Stream ended — flush bundled/remainder text (if any) and reset.
    if (streamBuffer || streamPending || streamShippedFirst) flushStreamBuffer();
  } else if (partial.length > streamBuffer.length) {
    // New tokens arrived — replace the buffer with the latest snapshot.
    // (gameStore stores the cumulative partial text, not the delta.)
    streamBuffer = partial;
    const { sentences, remainder } = splitSentences(streamBuffer);
    for (const s of sentences) {
      // Remember every sentence so the final full-line appendLog is
      // recognised as already-spoken (dedup is substring-based).
      rememberStreamed(s);
      if (!streamShippedFirst) {
        // First sentence ships immediately → audio starts fast.
        speakArbiter(s);
        streamShippedFirst = true;
      } else {
        // Bundle the rest so Kokoro reads multi-sentence chunks.
        streamPending = streamPending ? `${streamPending} ${s}` : s;
        if (streamPending.length >= STREAM_BUNDLE_CHARS) {
          speakArbiter(streamPending);
          streamPending = '';
        }
      }
    }
    streamBuffer = remainder;
  } else if (partial.length < streamBuffer.length) {
    // The store reset the partial text (e.g. submitPlayerAction
    // cancelled the in-flight generation). Drop our buffer + bundle.
    streamBuffer = partial;
    streamPending = '';
    streamShippedFirst = false;
  }
}

/** Bind the controller to the game store + settings observer. Call
 *  once at app boot, AFTER initTTSManager(). */
export function startTTSController(): void {
  if (unsub) return;
  controllerStartedAt = Date.now();
  syncToCurrent(useGameStore.getState());
  unsub = useGameStore.subscribe(onState);
  // engine_Dev — tear the voice down when the app loses the foreground (see
  // onAppStateChange). Tolerate older RN return shapes (void) defensively.
  lastAppState = AppState.currentState ?? 'active';
  appStateSub = AppState.addEventListener('change', onAppStateChange) as { remove: () => void } | null;
  // arb54 — voice diagnostics → game log. Fires immediately with the current
  // state (so a boot-time download failure shows up right away), then on each
  // transition. Errors always log (each retry); other phases log once.
  {
    const vs = getVoiceSettings();
    logVoice(`voice: engine=${vs.engine} tts=${vs.ttsEnabled ? 'on' : 'off'} voice=${vs.kokoroVoice ?? 'default'}`);
    unsubKokoro = onKokoroStateChange((s) => {
      if (s.phase === 'downloading' && lastVoicePhase === 'downloading') return; // skip fraction spam
      if (s.phase === lastVoicePhase && s.phase !== 'error') return;
      lastVoicePhase = s.phase;
      if (s.phase === 'error') {
        const e = getKokoroErrorHistory()[0];
        logVoice(`voice: bundled FAILED at ${e?.step ?? '?'} — ${s.message}${e ? ` (free ${e.diskFreeMB}MB)` : ''}; falling back to system voice`);
      } else {
        logVoice(`voice: bundled ${s.phase}`);
      }
    });
  }
  unsubSettings = onVoiceSettingsChange((s) => {
    if (!s.ttsEnabled) {
      // Settings flipped OFF — manager handles the queue (keeps the
      // current sentence, drops the rest); we just resync indices so
      // an OFF→ON toggle doesn't replay anything.
      syncToCurrent(useGameStore.getState());
    }
  });
}

export function stopTTSController(): void {
  if (unsub) { unsub(); unsub = null; }
  if (unsubSettings) { unsubSettings(); unsubSettings = null; }
  if (unsubKokoro) { unsubKokoro(); unsubKokoro = null; }
  if (appStateSub) { try { appStateSub.remove(); } catch { /* ignore */ } appStateSub = null; }
  lastVoicePhase = null;
  stopAndClear();
}
