// Metro config bump only -- fires android-build workflow so a fresh APK ships the latest app/** state.
//
// 2026-05-15a: initial dual-workflow pipeline (OTA fast, APK slow, path-gated triggers)
// 2026-05-15b: patch Kotlin 1.9.24 -> 1.9.25 in android/build.gradle for Compose compiler compat
// 2026-05-15c: interactive dice roller — player rolls each die, enemy counter-attacks on miss/wound
// 2026-05-15d: Kotlin patch — sed both quote styles + gradle -Pandroid.kotlinVersion + KOTLIN_VERSION env + debug grep
// 2026-05-15e: replace sed hacks with gradle.properties append (canonical mechanism) and strip commit message from build logs/release notes
// 2026-05-15f: proper Kotlin fix — expo-build-properties plugin sets 1.9.25 at prebuild time; sed + suppressCheck as belt-and-suspenders
// 2026-05-15g: REAL root cause — patch kotlin=1.9.24 → 1.9.25 in node_modules libs.versions.toml (RN + gradle-plugin) before prebuild
// 2026-05-15h: pin onnxruntime-android to 1.20.0 (avoid latest.integration → maven-metadata.xml SAX bug)
// 2026-05-15i: bump onnxruntime-android pin to 1.22.0 — 1.20.0 missing Ort::Value() default ctor + zero-arg GetSymbolicDimensions used by JS bindings
// 2026-05-15j: APK refresh — ship cumulative OTA work since last APK (lore-aware Arbiter, stamina, multi-slot saves, investigate split). OTAs not landing on device; APK update unblocks playtest while we diagnose.
// 2026-05-15k: APK refresh #2 — bake in the combat-narration fixes (parser combat override, weapon-aware narration, Arbiter combat awareness, enemy stat block with HP bar, multi-slot save system). OTAs still unconfirmed; ship as native binary.
// 2026-05-15l: HOTFIX APK — multi-slot save load lost currentScene, leaving "No scene" + every action silently no-oping. hydrate / loadSlotIntoGame now beginScene() on restore; submitPlayerAction auto-recovers if scene is null.
// 2026-05-15m: APK refresh — adds CHECK FOR OTA UPDATE button on About screen + live Updates.* diagnostics (runtimeVersion, channel, updateId, isEnabled, isEmbeddedLaunch). User can manually pull OTAs when automatic check-on-load fails.
// 2026-05-15n: APK refresh — About screen rewrite. APK build number from native versionCode (set by build-apk.yml from github.run_number), last OTA applied + published-at timestamp from Updates.* live values, cleaned up the "policy" object display. expo-application 6.0.0 added.
// 2026-05-15o: APK refresh — always start at main menu (no auto-resume), permadeath marks character "DEAD" on slot list instead of erasing, Resurrection Gems dropped ~0.5% per kill saved install-wide, dead slots gated behind gem spend.
// 2026-05-15p: APK refresh — Arbiter now actively shapes story. Proactive scene-intro narration (~45% on scene start, combat-aware when enemy is staged) gestures at what to do here, not just describes what's here. Soft-fallback inventory hint replaced with contextual scoring (low HP → food, dark hazard → light, curious mood → detection items, combat → weapons). The Arbiter mentions things because they matter, not at random.
// 2026-05-15q: APK refresh — item catalogue (13 weapons / 8 armor / 17 materials / 6 gear / 8 recipes) + crafting system. Player can type 'craft' alone to list buildable items, or 'craft <name>' to forge one. Arbiter watches inventory after each enemy kill and announces newly-unlocked recipes. Materials match existing enemy loot drop names so the loop integrates with current scenes.
// 2026-05-15r: APK refresh — phase boundary marker. Confirms cumulative state with catalogue + crafting + ask-the-Arbiter + race/faction/timeline awareness + roll labels + milestones + DEAD badge + Resurrection Gems + always-start-menu + scene-restore + multi-slot saves + lore-aware Arbiter + stamina + investigate split + enemy stat block + MiniLM cognitive layer + everything cumulative.
// 2026-05-15s: APK refresh — Phase A. Equip system + combat damage types. Player can 'equip <weapon/armor>' and 'unequip'; combat reads equipped weapon for damage dice + damageType + stat; enemy resistances/weaknesses by type (Mud Creature weak to Burn, Automation weak to Electrical, etc.) apply ×0.5 or ×1.5 with a combat log line explaining; armor resistances halve matching incoming damage; AC includes armor.acBonus everywhere. StatsPanel shows Equipped row + effective AC.
// 2026-05-15t: APK refresh — Phase B. Vendor encounters + active TC economy. 4 vendor archetypes (Reclaimer scrap broker, Forgotten Order scholar, True Tartarian quartermaster, wandering drifter) appear ~22% of peaceful scenes with 4-6 items each from the catalogue. New VendorPanel UI in ExplorationScreen with tap-to-buy, confirm Alert, dismiss. TC drops from enemies (30%/kill, scaled by rarity). buyFromVendor/dismissVendor actions on store.
// 2026-05-15u: APK refresh — Phase C. Social systems. Faction reputation now actively tracked: buy (+1), gift (+5), caught stealing (-10), with half-propagation to allies / inverse to rivals via factions.ts engine. New parser intents: gift, steal, join. 'gift <item>' transfers from inventory to vendor and shifts rep. 'steal <item>' does a d20+DEX vs DC 12 stealth check — success palms the item, failure logs a CAUGHT line and the vendor leaves. 'join <faction>' switches your factionId if standing ≥ 20.
// 2026-05-15v: APK refresh — Phase D. Combat status effects (piercing → bleed DOT, slashing → -2 AC, burn → aetheric vulnerability, electrical → paralyze, stun → skip turn, poison → -2 attack) applied probabilistically per damage type, tick at start of each player action with DOT damage logged, incapacitation wastes the turn. Status visible on StatsPanel. Memorable events tracker on WorldMemory captures faction_join / death_revive / rare_kill / theft_caught / first_kill, Arbiter references the most recent one in scene intros.
// 2026-05-15w: APK refresh — Phase E. UX rework. Full-screen InventoryScreen with color-coded categories (weapon/armor/consumable/relic/material/loot) + legend + back button + equipped markers. Context-aware quick buttons (look/search/rest/inventory out of combat; punch/kick/weapon/dodge in combat). Dodge gives +4 AC for one round via status effect. Top-right slot now shows EnemyPanel when in combat or a Tartarian crest placeholder otherwise. Inventory button opens the screen instead of logging the useless "Pack is on the right" line. Day/night counter ticks on rest (4-7 hours per rest), scene bar shows "Day N · time". EnemyPanel cards are tappable to cycle when multi-enemy + show IN RANGE / OUT OF RANGE badge.
// 2026-05-15x: APK refresh — Multi-slot equipment + tap-to-equip + per-weapon combat buttons. PlayerEquipped expanded from {weapon, armor} to {main, off, armor, amulet, ring}. Tap an item in InventoryScreen to equip; weapons prompt for main/off; legacy saves migrate via backfillPlayer. StatsPanel shows all filled slots. InputBox combat row renders a button per equipped weapon by name (truncated label), 'attack with the off-hand X' routes to the off-hand weapon. equipment.ts engine module computes valid slots per item.
// 2026-05-16y: APK refresh — Phase F cumulative. 8-slot armor (head/chest/legs/feet) with summed AC + aggregated resistances. Amulets (5) and Rings (5) catalogs with stat bonuses + resistances feeding effectiveStats() into all combat math. Combat ranges (arm's reach / close / far) with advance / step-back verbs, weapon-reach gating, live range readout on EnemyPanel. Durability tracking on weapons + armor + accessories with stampDurability on buy/craft/steal, wear on hit / hit-taken, auto-unequip on break, vendor repair flow (TC = missing points). Faction quests fully wired — vendors pitch contracts, accept / turn in verbs, contracts line in StatsPanel. 4 new lore-canonical vendors (Thalan, Irma, Jorah, Halem, Tarek, Felra, Velar, Elara) + important NPCs (Elior Zalmar, Harlan Moore, Sasha Ironheart, Drake Volkov, Ivy Solis, Lucius Kincaid, Varakush, Grand Assembly Speaker). Time clock advances on every action — attack (0.1h), skill check (0.25h), eat (0.5h), wander (1h), travel (2h). Multi-agent audit pass fixed orphaned vendor offers (Patched Cloth + Runic Mantle + Mud-glass Scales now in catalog), recipe name drift (Aetherstone Vest → Aetheric Vest), constitution stat silent-drop (Mud Warden Amulet → wisdom), off-hand attack now actually wears the off weapon, stale-player applyEnemyCounter calls now read fresh state, eat-ration now advances time, contracts-line falls back gracefully on unknown ids, DiceRoller TS error fixed. 71 passing tests, zero type errors.
// 2026-05-16aa: APK refresh — Tartaria crest icon. Added assets/icon.png (1024×1024) and wired as app.json `icon` + Android `adaptiveIcon.foregroundImage`. CrestPlaceholder (top-right slot when out of combat) and TitleScreen now display the crest. OTA also ships the JS bits for devices already on the previous APK.
// 2026-05-16z: APK refresh — Phase G CUMULATIVE. STATEFUL NARRATIVE HOOKS: 27 lore-canonical kinds (smoke / footprints / obelisk / wagon / arch / glint / handprint / thread / resonance / half_buried_spire / etheric_storm / pulsing_mud / frozen_statue / sentinel_patrol / mud_golem_stir / temporal_eddy / spatial_warp / whisper_crystal / black_cloak / giant_silhouette / bioluminescent_path / wreck_construct / submerged_steeple / black_market_lantern / aether_grid_hum / sealed_vault_door / preserved_corpse) with 2-3 stage chains, cross-scene continuation via worldMemory.pendingChains, Arbiter callbacks referencing live threads. MONSTER HUNTS: 5 lore-grounded 7-8 stage hunts (Bog Dragon / Mud Titan / Sludge Behemoth / Iron Titan / Mud Siren Queen) with bosses that scale to player hpMax. MYSTERY OBJECTS: 5 lore-canonical 3-5 stage quests (Red Tower Fragment / Cradle Compass / Leviathan Eye / Temporal Watch / Shifting Obsidian Orb). FACTION STORYLINES: 4 long-form 7-10 stage faction storylines (Order's Red Tower's Mouth / Tartarian Path of Ascension / Reclaimer Relic Run / Monarch Silence Across the Border) for major faction rep gain. WEATHER EFFECTS: every action rolls weather pressure — Etheric Storm = electrical dmg, Ash Storm = stamina drain, Glass Hail = chip dmg, Whisper Fog = corruption, Iron Fog + Silent Blizzard block repositioning. DIG SYSTEM: 'dig' verb / quick button, per-item digScore, RNG loot table weighted by tool, dig damage scales with brittleness (tradeoff: brittle knife digs fast but breaks faster than a spear). PROCEDURAL WORLD MAP: deterministic 21×21 grid per character (mapSeed from name+race+faction+timestamp), 21 locations spread sparsely (most movement is open ground). Directional travel ('go north') walks the grid, compass in inventory unlocks 'where am I' surveys. STARTER KITS: race-themed primary weapon (Mud-fist Wraps / Rusted Blade / Tartarian Spear / Pyric Wand) + faction-themed cheap knife (Reclaimer's Trowel / Order Letter-Opener / Bone Shiv / Pocket Knife). 84 passing tests (+13 new), zero type errors. All vendor / recipe / hunt / mystery / storyline cross-references resolve.

const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

module.exports = config;
